import Link from 'next/link'
import './globals.css'
import { Control } from './Control'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
    // fetch('http://localhost:9999/topics')
    // .then(resp=>resp.json())
    // .then(result=>{
    //   setTopics(result);
    // });
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics', {cache:'no-store'});
  const topics = await resp.json();
  return (
    <html lang="en">
      <body>
      <h1><Link href="/">WEB</Link></h1>  
      <ol>
        {topics.map((topic, i)=>{
          return <li ttt={i} key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
        })}
      </ol>
        {children}
        <Control />
      </body>
    </html>
  )
}
